In [1]:
!pip install firebase-admin
!pip install mlxtend
!pip install wordcloud

Requirement already satisfied: firebase-admin in c:\users\codelabs\anaconda3\lib\site-packages (4.3.0)
Requirement already satisfied: google-api-python-client>=1.7.8 in c:\users\codelabs\anaconda3\lib\site-packages (from firebase-admin) (1.9.3)
Requirement already satisfied: google-cloud-storage>=1.18.0 in c:\users\codelabs\anaconda3\lib\site-packages (from firebase-admin) (1.29.0)
Requirement already satisfied: google-cloud-firestore>=1.4.0; platform_python_implementation != "PyPy" in c:\users\codelabs\anaconda3\lib\site-packages (from firebase-admin) (1.8.1)
Requirement already satisfied: cachecontrol>=0.12.6 in c:\users\codelabs\anaconda3\lib\site-packages (from firebase-admin) (0.12.6)
Requirement already satisfied: google-api-core[grpc]<2.0.0dev,>=1.14.0; platform_python_implementation != "PyPy" in c:\users\codelabs\anaconda3\lib\site-packages (from firebase-admin) (1.16.0)
Requirement already satisfied: httplib2<1dev,>=0.9.2 in c:\users\codelabs\anaconda3\lib\site-packages (from google-api-python-client>=1.7.8->firebase-admin) (0.18.1)
Requirement already satisfied: uritemplate<4dev,>=3.0.0 in c:\users\codelabs\anaconda3\lib\site-packages (from google-api-python-client>=1.7.8->firebase-admin) (3.0.1)
Requirement already satisfied: google-auth-httplib2>=0.0.3 in c:\users\codelabs\anaconda3\lib\site-packages (from google-api-python-client>=1.7.8->firebase-admin) (0.0.4)
Requirement already satisfied: six<2dev,>=1.6.1 in c:\users\codelabs\anaconda3\lib\site-packages (from google-api-python-client>=1.7.8->firebase-admin) (1.14.0)
Collecting google-auth>=1.16.0 (from google-api-python-client>=1.7.8->firebase-admin)
  Downloading https://files.pythonhosted.org/packages/0f/79/4c59796bb02535aee5e5d2e2c5e16008aaf48903c2ec2ff566a2774bb3e0/google_auth-1.20.1-py2.py3-none-any.whl (91kB)
Requirement already satisfied: google-cloud-core<2.0dev,>=1.2.0 in c:\users\codelabs\anaconda3\lib\site-packages (from google-cloud-storage>=1.18.0->firebase-admin) (1.3.0)
Requirement already satisfied: google-resumable-media<0.6dev,>=0.5.0 in c:\users\codelabs\anaconda3\lib\site-packages (from google-cloud-storage>=1.18.0->firebase-admin) (0.5.0)
Requirement already satisfied: pytz in c:\users\codelabs\anaconda3\lib\site-packages (from google-cloud-firestore>=1.4.0; platform_python_implementation != "PyPy"->firebase-admin) (2019.3)
Requirement already satisfied: requests in c:\users\codelabs\anaconda3\lib\site-packages (from cachecontrol>=0.12.6->firebase-admin) (2.22.0)
Requirement already satisfied: msgpack>=0.5.2 in c:\users\codelabs\anaconda3\lib\site-packages (from cachecontrol>=0.12.6->firebase-admin) (0.6.1)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in c:\users\codelabs\anaconda3\lib\site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0; platform_python_implementation != "PyPy"->firebase-admin) (1.51.0)
Requirement already satisfied: protobuf>=3.4.0 in c:\users\codelabs\anaconda3\lib\site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0; platform_python_implementation != "PyPy"->firebase-admin) (3.11.4)
Requirement already satisfied: setuptools>=34.0.0 in c:\users\codelabs\anaconda3\lib\site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0; platform_python_implementation != "PyPy"->firebase-admin) (41.4.0)
Requirement already satisfied: grpcio<2.0dev,>=1.8.2; extra == "grpc" in c:\users\codelabs\anaconda3\lib\site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0; platform_python_implementation != "PyPy"->firebase-admin) (1.30.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\codelabs\anaconda3\lib\site-packages (from google-auth>=1.16.0->google-api-python-client>=1.7.8->firebase-admin) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.5" in c:\users\codelabs\anaconda3\lib\site-packages (from google-auth>=1.16.0->google-api-python-client>=1.7.8->firebase-admin) (4.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\users\codelabs\anaconda3\lib\site-packages (from google-auth>=1.16.0->google-api-python-client>=1.7.8->firebase-admin) (4.1.0)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\codelabs\anaconda3\lib\site-packages (from requests->cachecontrol>=0.12.6->firebase-admin) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\codelabs\anaconda3\lib\site-packages (from requests->cachecontrol>=0.12.6->firebase-admin) (2019.9.11)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\codelabs\anaconda3\lib\site-packages (from requests->cachecontrol>=0.12.6->firebase-admin) (1.24.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\codelabs\anaconda3\lib\site-packages (from requests->cachecontrol>=0.12.6->firebase-admin) (3.0.4)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\codelabs\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.16.0->google-api-python-client>=1.7.8->firebase-admin) (0.4.8)
Installing collected packages: google-auth
  Found existing installation: google-auth 1.13.1
    Uninstalling google-auth-1.13.1:
      Successfully uninstalled google-auth-1.13.1
Successfully installed google-auth-1.20.1

ERROR: google-api-python-client 1.9.3 has requirement google-api-core<2dev,>=1.18.0, but you'll have google-api-core 1.16.0 which is incompatible.

Requirement already satisfied: mlxtend in c:\users\codelabs\anaconda3\lib\site-packages (0.17.2)
Requirement already satisfied: setuptools in c:\users\codelabs\anaconda3\lib\site-packages (from mlxtend) (41.4.0)
Requirement already satisfied: scikit-learn>=0.20.3 in c:\users\codelabs\anaconda3\lib\site-packages (from mlxtend) (0.21.3)
Requirement already satisfied: scipy>=1.2.1 in c:\users\codelabs\anaconda3\lib\site-packages (from mlxtend) (1.3.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\codelabs\anaconda3\lib\site-packages (from mlxtend) (1.16.5)
Requirement already satisfied: pandas>=0.24.2 in c:\users\codelabs\anaconda3\lib\site-packages (from mlxtend) (0.25.1)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\codelabs\anaconda3\lib\site-packages (from mlxtend) (3.2.1)
Requirement already satisfied: joblib>=0.13.2 in c:\users\codelabs\anaconda3\lib\site-packages (from mlxtend) (0.13.2)
Requirement already satisfied: pytz>=2017.2 in c:\users\codelabs\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\codelabs\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2.8.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\codelabs\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.1.0)
Requirement already satisfied: cycler>=0.10 in c:\users\codelabs\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\codelabs\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.4.2)
Requirement already satisfied: six>=1.5 in c:\users\codelabs\anaconda3\lib\site-packages (from python-dateutil>=2.6.1->pandas>=0.24.2->mlxtend) (1.14.0)
Requirement already satisfied: wordcloud in c:\users\codelabs\anaconda3\lib\site-packages (1.6.0)
Requirement already satisfied: matplotlib in c:\users\codelabs\anaconda3\lib\site-packages (from wordcloud) (3.2.1)
Requirement already satisfied: numpy>=1.6.1 in c:\users\codelabs\anaconda3\lib\site-packages (from wordcloud) (1.16.5)
Requirement already satisfied: pillow in c:\users\codelabs\anaconda3\lib\site-packages (from wordcloud) (6.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\codelabs\anaconda3\lib\site-packages (from matplotlib->wordcloud) (2.4.2)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\codelabs\anaconda3\lib\site-packages (from matplotlib->wordcloud) (2.8.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\codelabs\anaconda3\lib\site-packages (from matplotlib->wordcloud) (1.1.0)
Requirement already satisfied: cycler>=0.10 in c:\users\codelabs\anaconda3\lib\site-packages (from matplotlib->wordcloud) (0.10.0)
Requirement already satisfied: six>=1.5 in c:\users\codelabs\anaconda3\lib\site-packages (from python-dateutil>=2.1->matplotlib->wordcloud) (1.14.0)
Requirement already satisfied: setuptools in c:\users\codelabs\anaconda3\lib\site-packages (from kiwisolver>=1.0.1->matplotlib->wordcloud) (41.4.0)

In [12]:
!pip install binarytree

Collecting binarytree
  Downloading https://files.pythonhosted.org/packages/80/cf/09e363df1fbdfbf1413f1c737a7da8ce22559456b3ac520ba3008fef2996/binarytree-5.1.0-py2.py3-none-any.whl
Installing collected packages: binarytree
Successfully installed binarytree-5.1.0

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import csv
from collections import defaultdict

import re

import os

import matplotlib.pyplot as plt


from mlxtend.frequent_patterns import fpgrowth
# from mlxtend.frequent_patterns import apriori

In [2]:
import firebase_admin
from firebase_admin import credentials, db

In [46]:
cred = credentials.Certificate("./sdk-firebase.json")
firebase_admin.initialize_app(cred, {
    'databaseURL' : 'https://tanahairku-experimental-cl.firebaseio.com/'
})

ValueError: The default Firebase app already exists. This means you called initialize_app() more than once without providing an app name as the second argument. In most cases you only need to call initialize_app() once. But if you do want to initialize multiple apps, pass a second argument to initialize_app() to give each app a unique name.

In [47]:
ref = firebase_admin.db.reference("/users")


data = ref.get()
log_data = []
for userid in data:
   for id_log in data[userid]['log'] :
     log_data.append([
       data[userid]['log'][id_log]['Date'],
       id_log,
       data[userid]['log'][id_log]['Items_Interval'],
       data[userid]['log'][id_log]['Items_Log'],
     ])

In [5]:
df = pd.DataFrame(log_data)

In [7]:
new_names = {0 : 'tgl_akses',
             1 : 'id_user',
             2 : 'durasiAkses',
             3 : 'konten'
            }
df.rename(columns=new_names, inplace=True)

In [17]:
#hapus data 
df.drop(df[df.durasiAkses == '0'].index, inplace=True)
df.dropna()

,tgl_akses,id_user,durasiAkses,konten
0,13-02-2020,-M-wZQJsrdMbk7RBbm8y,"0, 47, 30, 1, 28, 3, 41","START, Pakaian_Asmat, Rumah_Asmat, Senjata_Asm..."
1,10-02-2020,-M-hRtw0uP1Z2JmrT3F1,"0, 1, 10, 17","START, Senjata_Sunda, Senjata_Sunda, Senjata_S..."
2,10-02-2020,-M-hURASU2ZRo-p_-cdt,"0, 1, 6, 3, 6, 11, 17, 3, 7, 8, 9, 5, 3, 38, 3...","START, Musik_Bali, Pakaian_Aceh, Pakaian_Aceh,..."
3,08-02-2020,-M-Zr7vUwWA7b9FqEhdV,"0, 7, 13, 5, 11","START, Pakaian_Toraja, Pakaian_Toraja, Pakaian..."
4,08-02-2020,-M-Zrp0nHiE9FrHTc5YK,"0, 7, 13, 14, 40, 12","START, Rumah_Aceh, Pakaian_Aceh, Pakaian_Aceh,..."
5,10-02-2020,-M-hGMgsnFPZC2yMiC2X,"0, 4, 11, 15, 8, 2, 10, 8, 7, 0, 3, 1, 8, 2, 2...","START, Rumah_Aceh, Rumah_Aceh, Rumah_Aceh, Pak..."
6,10-02-2020,-M-hIWAwtJMSZ3l_-YZC,"0, 14, 1, 14","START, Senjata_Sunda, Rumah_Sunda, Senjata_Sunda"
7,10-02-2020,-M-hKE9xgX3OyizMNLWT,"0, 19, 5, 34, 90, 7, 49, 27, 7, 17, 7, 47, 13,...","START, Rumah_Aceh, Rumah_Aceh, Rumah_Aceh, Mus..."
8,10-02-2020,-M-hM5Xa99iZpcVRt58m,"0, 17, 103, 77, 7, 7, 11, 6, 4, 12, 4, 11, 31,...","START, Pakaian_Aceh, Pakaian_Aceh, Makanan_Sun..."
9,10-02-2020,-M-hO5qpm4Zgst4c0vSd,"0, 6, 79, 7, 39, 32, 43, 27, 24, 58, 32","START, Rumah_Aceh, Rumah_Aceh, Rumah_Aceh, Pak..."
10,10-02-2020,-M-hQ3YHYGjn7cEwOAno,"0, 12, 17, 13, 1, 8, 15, 2, 6, 4, 18, 51, 17, ...","START, Pakaian_Sunda, Rumah_Bali, Rumah_Bali, ..."
11,10-02-2020,-M-hRGLm-qNL8Ee308dF,"0, 41, 27, 28, 0, 22, 18, 10, 10, 58, 2, 10, 8...","START, Rumah_Aceh, Rumah_Aceh, Pakaian_Aceh, P..."
12,10-02-2020,-M-hT4ud_0qpXUnf9BwA,"0, 57, 39, 10, 127, 31, 11, 23, 2, 76","START, Makanan_Aceh, Makanan_Sunda, Rumah_Bali..."
13,10-02-2020,-M-hlvmhTgkm4qa2RcYV,"0, 56, 50, 53, 23, 35, 24, 24, 4","START, Rumah_Aceh, Pakaian_Aceh, Musik_Aceh, M..."
14,10-02-2020,-M-hnHCX-u7kklukGmqu,"0, 71, 35, 35, 22, 25, 12, 6","START, Pakaian_Aceh, Pakaian_Sunda, Musik_Sund..."
15,10-02-2020,-M-hobFwmKJjMQo0PtPm,"0, 18, 73, 35, 31, 14, 17, 23","START, Rumah_Aceh, Pakaian_Aceh, Musik_Aceh, M..."
16,10-02-2020,-M-hpY79CGTArVJSEs0n,"0, 34, 5, 33, 18, 10, 41, 18, 15, 14","START, Senjata_Sunda, Senjata_Sunda, Musik_Sun..."
17,10-02-2020,-M-hqi9hVD1GP88sNihE,"0, 46, 4, 73, 76, 79, 6, 78, 50, 14, 14","START, Musik_Aceh, Makanan_Dayak, Makanan_Daya..."
18,10-02-2020,-M-hsmLWNECfN9zdxAfj,"0, 18, 2, 4, 9, 1, 27, 1, 3, 12, 34, 14, 13, 0...","START, Rumah_Toraja, Rumah_Toraja, Rumah_Toraj..."
19,10-02-2020,-M-hurdaCZE3vuf3rDHu,"0, 1, 9, 2, 3, 1, 10, 17, 6, 44, 42, 5, 6, 32,...","START, Musik_Aceh, Musik_Aceh, Senjata_Sunda, ..."
20,10-02-2020,-M-hwLlC6gFDP5deVZ-O,"0, 50, 19, 3, 3, 4, 11, 8, 2, 16, 8, 127, 21, ...","START, Pakaian_Aceh, Musik_Aceh, Musik_Aceh, M..."
21,10-02-2020,-M-hy8vucRZS8Ax9E9la,"0, 7, 73, 4, 40, 9, 8, 25, 17, 8, 14, 5, 2, 2,...","START, Rumah_Bali, Rumah_Bali, Pakaian_Bali, P..."
22,11-02-2020,-M-lz8V2bkmdY-MmB-Wy,"0, 61, 11, 87, 58, 32, 33, 61, 43, 89, 3, 69, ...","START, Rumah_Aceh, Makanan_Aceh, Makanan_Aceh,..."
23,11-02-2020,-M-m0u0KuoAjUT5O3_X1,"0, 11, 27, 19, 107, 25","START, Rumah_Sunda, Rumah_Sunda, Rumah_Sunda, ..."
24,11-02-2020,-M-m2KvIMJkojkSvvC3k,"0, 87, 44, 5, 37, 43, 2, 43","START, Musik_Sunda, Pakaian_Dayak, Pakaian_Bal..."
25,11-02-2020,-M-m8hawmREgqOCo9Qo-,"0, 13, 4, 11, 3, 1, 14, 25, 3, 46, 11, 26, 31,...","START, Rumah_Aceh, Rumah_Aceh, Pakaian_Aceh, P..."
26,11-02-2020,-M-mAg26JpnDCrKy3yT8,"0, 56, 12, 35, 42, 22, 17, 74","START, Rumah_Aceh, Rumah_Sunda, Rumah_Sunda, R..."
27,11-02-2020,-M-mBobmr5E1tregkdWL,"0, 3, 48, 3, 10, 4, 4, 14, 1, 8, 41, 45, 11, 20","START, Pakaian_Aceh, Pakaian_Aceh, Pakaian_Ace..."
28,11-02-2020,-M-mD_UDgjW25zUmJmUn,"0, 25, 20, 14, 23, 2, 6, 4, 2, 7, 13, 4, 2, 34...","START, Rumah_Aceh, Rumah_Toraja, Pakaian_Dayak..."
29,11-02-2020,-M-mRC6sbRZ_vZEaxDZb,"0, 6, 19, 25, 25, 49, 22, 20, 21, 11, 19, 15, ...","START, Rumah_Aceh, Rumah_Aceh, Pakaian_Aceh, M..."
30,11-02-2020,-M-mST-oVoTb2aMm_hE8,"0, 10, 7, 9, 15, 24, 6, 3, 1, 7, 15, 27, 13, 1...","START, Makanan_Sunda, Makanan_Bali, Makanan_Da..."
31,11-02-2020,-M-mTSzTgdCG0S-qA2aF,"0, 2, 22, 16, 32, 18, 14, 26, 31, 12, 7, 22","START, Rumah_Aceh, Rumah_Aceh, Rumah_Aceh, Rum..."
32,11-02-2020,-M-mUOUw3o6nVeOW-XQw,"0, 36, 24, 5, 9, 61, 28, 34, 31, 23, 26","START, Rumah_Aceh, Musik_Aceh, Rumah_Aceh, Sen..."
33,11-02-2020,-M-mVpHxcF0LkK_u88g9,"0, 19, 11, 17, 32, 21, 9, 14","START, Makanan_Sunda, Makanan_Bali, Musik_Aceh..."
34,25-07-2020,-MD3bnwZeeKaiLTdyTA1,"0, 34, 25, 35, 47, 48, 36, 22, 47, 22, 25, 33","START, Pakaian_Toraja, Makanan_Toraja, Musik_T..."
35,25-07-2020,-MD3e8xQutdRB2E6iFoA,"0, 28, 45, 27, 18, 31, 20, 16, 64, 100, 6, 40,...","START, Rumah_Sunda, Makanan_Aceh, Musik_Aceh, ..."
36,25-07-2020,-MD3i54UmiC8v70wl5U-,"0, 70, 17, 20, 19, 39, 10, 34, 13, 18","START, Rumah_Toraja, Makanan_Dayak, Rumah_Sund..."
37,25-07-2020,-MD3jFOcyR-TJ9BmzqCM,"0, 24, 32, 14, 38, 55, 68, 36, 48, 30, 17, 17,...","START, Pakaian_Bali, Pakaian_Bali, Pakaian_Bal..."

In [18]:
new_konten = [konten.replace('START, ', '') for konten in df.konten]

In [48]:
dataset = []
for x in new_konten:
  dataset.append(x.split(", "))

In [22]:
# a_list = dataset

# frequencies = {}
# for item in a_list:
#     if item in frequencies:
#         frequencies[item] += 1
#     else:
#         frequencies[item] = 1

# # print(frequencies)

In [49]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)

In [115]:
sum(df.Musik_Dayak== True)

6

In [51]:
frequent_itemsets_fp = fpgrowth(df, min_support=0.3, use_colnames=True)
frequent_itemsets_fp['length'] = frequent_itemsets_fp['itemsets'].apply(lambda x:len(x))
itemsetFP = frequent_itemsets_fp

In [52]:
itemsetFP.sort_values(by='support',ascending=False)

     support                                itemsets  length
1   0.578947                            (Musik_Aceh)       1
2   0.552632                          (Rumah_Toraja)       1
3   0.500000                           (Rumah_Sunda)       1
4   0.500000                            (Rumah_Aceh)       1
5   0.500000                          (Pakaian_Aceh)       1
6   0.447368                          (Makanan_Bali)       1
7   0.447368                         (Pakaian_Sunda)       1
13  0.421053                           (Musik_Sunda)       1
19  0.421053                (Musik_Aceh, Rumah_Aceh)       2
12  0.421053                            (Rumah_Bali)       1
21  0.394737              (Musik_Aceh, Pakaian_Aceh)       2
9   0.368421                         (Makanan_Dayak)       1
16  0.368421                         (Makanan_Sunda)       1
17  0.368421              (Musik_Aceh, Rumah_Toraja)       2
18  0.368421             (Rumah_Sunda, Rumah_Toraja)       2
8   0.368421                         (Pakaian_Dayak)       1
25  0.342105           (Pakaian_Sunda, Pakaian_Aceh)       2
28  0.342105              (Rumah_Bali, Rumah_Toraja)       2
11  0.342105                          (Makanan_Aceh)       1
22  0.342105              (Rumah_Aceh, Pakaian_Aceh)       2
26  0.315789             (Pakaian_Sunda, Musik_Aceh)       2
24  0.315789              (Musik_Aceh, Makanan_Bali)       2
27  0.315789           (Makanan_Dayak, Rumah_Toraja)       2
0   0.315789                         (Senjata_Sunda)       1
23  0.315789  (Musik_Aceh, Rumah_Aceh, Pakaian_Aceh)       3
20  0.315789              (Rumah_Aceh, Rumah_Toraja)       2
15  0.315789                          (Senjata_Bali)       1
10  0.315789                        (Pakaian_Toraja)       1
14  0.315789                          (Pakaian_Bali)       1

In [65]:
from mlxtend.frequent_patterns import association_rules

# rules_ap = association_rules(frequent_itemsets_ap, metric="confidence", min_threshold=0.8)
rules_fp = association_rules(itemsetFP, metric="confidence", min_threshold=0.6)
rules_fp
# sort_values(by='confidence', ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Musik_Aceh),(Rumah_Toraja),0.578947,0.552632,0.368421,0.636364,1.151515,0.048476,1.230263
1,(Rumah_Toraja),(Musik_Aceh),0.552632,0.578947,0.368421,0.666667,1.151515,0.048476,1.263158
2,(Rumah_Sunda),(Rumah_Toraja),0.500000,0.552632,0.368421,0.736842,1.333333,0.092105,1.700000
3,(Rumah_Toraja),(Rumah_Sunda),0.552632,0.500000,0.368421,0.666667,1.333333,0.092105,1.500000
4,(Musik_Aceh),(Rumah_Aceh),0.578947,0.500000,0.421053,0.727273,1.454545,0.131579,1.833333
5,(Rumah_Aceh),(Musik_Aceh),0.500000,0.578947,0.421053,0.842105,1.454545,0.131579,2.666667
6,(Rumah_Aceh),(Rumah_Toraja),0.500000,0.552632,0.315789,0.631579,1.142857,0.039474,1.214286
7,(Musik_Aceh),(Pakaian_Aceh),0.578947,0.500000,0.394737,0.681818,1.363636,0.105263,1.571429
8,(Pakaian_Aceh),(Musik_Aceh),0.500000,0.578947,0.394737,0.789474,1.363636,0.105263,2.000000
9,(Rumah_Aceh),(Pakaian_Aceh),0.500000,0.500000,0.342105,0.684211,1.368421,0.092105,1.583333
10,(Pakaian_Aceh),(Rumah_Aceh),0.500000,0.500000,0.342105,0.684211,1.368421,0.092105,1.583333
11,"(Musik_Aceh, Rumah_Aceh)",(Pakaian_Aceh),0.421053,0.500000,0.315789,0.750000,1.500000,0.105263,2.000000
12,"(Musik_Aceh, Pakaian_Aceh)",(Rumah_Aceh),0.394737,0.500000,0.315789,0.800000,1.600000,0.118421,2.500000
13,"(Rumah_Aceh, Pakaian_Aceh)",(Musik_Aceh),0.342105,0.578947,0.315789,0.923077,1.594406,0.117729,5.473684
14,(Rumah_Aceh),"(Musik_Aceh, Pakaian_Aceh)",0.500000,0.394737,0.315789,0.631579,1.600000,0.118421,1.642857
15,(Pakaian_Aceh),"(Musik_Aceh, Rumah_Aceh)",0.500000,0.421053,0.315789,0.631579,1.500000,0.105263,1.571429
16,(Makanan_Bali),(Musik_Aceh),0.447368,0.578947,0.315789,0.705882,1.219251,0.056787,1.431579
17,(Pakaian_Sunda),(Pakaian_Aceh),0.447368,0.500000,0.342105,0.764706,1.529412,0.118421,2.125000
18,(Pakaian_Aceh),(Pakaian_Sunda),0.500000,0.447368,0.342105,0.684211,1.529412,0.118421,1.750000
19,(Pakaian_Sunda),(Musik_Aceh),0.447368,0.578947,0.315789,0.705882,1.219251,0.056787,1.431579
20,(Makanan_Dayak),(Rumah_Toraja),0.368421,0.552632,0.315789,0.857143,1.551020,0.112188,3.131579
21,(Rumah_Bali),(Rumah_Toraja),0.421053,0.552632,0.342105,0.812500,1.470238,0.109418,2.385965
22,(Rumah_Toraja),(Rumah_Bali),0.552632,0.421053,0.342105,0.619048,1.470238,0.109418,1.519737

In [58]:
a = rules_fp[['antecedents','consequents','support','confidence','lift']]
b = a.sort_values(by='lift', ascending=False)
b

# aaa = b[['support','confidence','lift']]

# for x in b.support:
#     print("{:10.4f}".format(x))

,antecedents,consequents,support,confidence,lift
12,"(Musik_Aceh, Pakaian_Aceh)",(Rumah_Aceh),0.315789,0.800000,1.600000
14,(Rumah_Aceh),"(Musik_Aceh, Pakaian_Aceh)",0.315789,0.631579,1.600000
13,"(Rumah_Aceh, Pakaian_Aceh)",(Musik_Aceh),0.315789,0.923077,1.594406
20,(Makanan_Dayak),(Rumah_Toraja),0.315789,0.857143,1.551020
18,(Pakaian_Aceh),(Pakaian_Sunda),0.342105,0.684211,1.529412
17,(Pakaian_Sunda),(Pakaian_Aceh),0.342105,0.764706,1.529412
11,"(Musik_Aceh, Rumah_Aceh)",(Pakaian_Aceh),0.315789,0.750000,1.500000
15,(Pakaian_Aceh),"(Musik_Aceh, Rumah_Aceh)",0.315789,0.631579,1.500000
21,(Rumah_Bali),(Rumah_Toraja),0.342105,0.812500,1.470238
22,(Rumah_Toraja),(Rumah_Bali),0.342105,0.619048,1.470238
5,(Rumah_Aceh),(Musik_Aceh),0.421053,0.842105,1.454545
4,(Musik_Aceh),(Rumah_Aceh),0.421053,0.727273,1.454545
10,(Pakaian_Aceh),(Rumah_Aceh),0.342105,0.684211,1.368421
9,(Rumah_Aceh),(Pakaian_Aceh),0.342105,0.684211,1.368421
8,(Pakaian_Aceh),(Musik_Aceh),0.394737,0.789474,1.363636
7,(Musik_Aceh),(Pakaian_Aceh),0.394737,0.681818,1.363636
3,(Rumah_Toraja),(Rumah_Sunda),0.368421,0.666667,1.333333
2,(Rumah_Sunda),(Rumah_Toraja),0.368421,0.736842,1.333333
16,(Makanan_Bali),(Musik_Aceh),0.315789,0.705882,1.219251
19,(Pakaian_Sunda),(Musik_Aceh),0.315789,0.705882,1.219251
0,(Musik_Aceh),(Rumah_Toraja),0.368421,0.636364,1.151515
1,(Rumah_Toraja),(Musik_Aceh),0.368421,0.666667,1.151515
6,(Rumah_Aceh),(Rumah_Toraja),0.315789,0.631579,1.142857

In [59]:
aa = ['(Rumah_Aceh)','(Rumah_Asmat)','(Rumah_Bali)','(Rumah_Dayak)','(Rumah_Sunda)','(Rumah_Toraja)',
              '(Musik_Aceh)','(Musik_Asmat)','(Musik_Bali)','(Musik_Dayak)','(Musik_Sunda)','(Musik_Toraja)',
              '((Makanan_Aceh)','(Makanan_Asmat)','(Makanan_Bali)','(Makanan_Dayak)','(Makanan_Sunda)','(Makanan_Toraja)',
              '(Senjata_Aceh)','(Senjata_Asmat)','(Senjata_Bali)','(Senjata_Dayak)','(Senjata_Sunda)','(Senjata_Toraja)',
              '(Pakaian_Aceh)','(Pakaian_Asmat)','(Pakaian_Bali)','(Pakaian_Dayak)','(Pakaian_Sunda)','(Pakaian_Toraja)']

In [60]:
pembanding = [['Rumah_Aceh'],['Rumah_Asmat'],['Rumah_Bali'],['Rumah_Dayak'],['Rumah_Sunda'],['Rumah_Toraja'],
              ['Musik_Aceh'],['Musik_Asmat'],['Musik_Bali'],['Musik_Dayak'],['Musik_Sunda'],['Musik_Toraja'],
              ['(Makanan_Aceh'],['Makanan_Asmat'],['Makanan_Bali'],['Makanan_Dayak'],['Makanan_Sunda'],['Makanan_Toraja'],
              ['Senjata_Aceh'],['Senjata_Asmat'],['Senjata_Bali'],['Senjata_Dayak'],['Senjata_Sunda'],['Senjata_Toraja'],
              ['Pakaian_Aceh'],['Pakaian_Asmat'],['Pakaian_Bali'],['Pakaian_Dayak'],['Pakaian_Sunda'],['Pakaian_Toraja']]

In [26]:
tolist_frozenset_antecedents = [list(x) for x in b['antecedents']]
tolist_frozenset_consequents = [list(x) for x in b['consequents']]

In [27]:
df_a = pd.DataFrame(tolist_frozenset_antecedents)
df_c = pd.DataFrame(tolist_frozenset_consequents)

In [28]:
concatAC = pd.concat([df_a,df_c], axis=1)

In [61]:
#hitung list dengan for
sum(string.count('Rumah_Bali') for string in tolist_frozenset_antecedents)

NameError: name 'tolist_frozenset_antecedents' is not defined

In [62]:
txt = str(tolist_frozenset_antecedents)
x = re.search("^Rumah", txt)
if x:
    print("Aya")
else:
    print("eweh")

NameError: name 'tolist_frozenset_antecedents' is not defined

In [49]:
#hitung list dengan lambda
subs = 'Rumah_Bali'
res = len([i for i in tolist_frozenset_consequents if subs in i])
res

NameError: name 'tolist_frozenset_consequents' is not defined

In [ ]:
df_pem = pd.DataFrame([pembanding,tolist_frozenset])

In [ ]:
trans_form = df_pem.T

In [ ]:
new_names = {0 : 'pembanding',
             1 : 'konten_pembanding'
            }
trans_form.rename(columns=new_names, inplace=True)

In [ ]:
list1 = trans_form.pembanding
list2 = trans_form.konten_pembanding

In [ ]:
def difference (list1, list2):
    list_dif = [i for i in list1 + list2 if i not in list1 or i not in list2]
    return list_dif

x = tuple(list1)
y = tuple(list2)

# print ("List first: " + str(x))
# print ("List second: " + str(y))

# Take difference of list 1 and list 2
z = difference (x, y)

print("Difference of first and second String: " + str(z))

if not z:
    print("First and Second list are Equal")
else:
    print("First and Second list are Not Equal")

In [13]:
my_dict = {'name': 'John', tuple([1,2,3]):'values'}
print(my_dict)

{'name': 'John', (1, 2, 3): 'values'}

In [14]:
listKonten = np.array(df.konten)

In [51]:
subs = 'Senjata_Sunda'
res = len([i for i in listKonten if subs in i])
res

12

In [53]:
from binarytree import build 
  
  
# List of nodes 
nodes =[13, 2, 2, 2, 13, 14, 1, 1, 1, 1, 19, 13, 4, 26, 30, 20, 25, 25, 21, 25, 4, 2] 
  
# Builidng the binary tree 
binary_tree = build(nodes) 
print('Binary tree from list :\n', 
      binary_tree) 
  
# Getting list of nodes from 
# binarytree 
print('\nList from binary tree :',  
      binary_tree.values)

Binary tree from list :

                    _______________13________
                   /                         \
          ________2_______                 ___2___
         /                \               /       \
     ___2___             __13__         _14       _1
    /       \           /      \       /   \     /  \
  _1        _1        _1        19    13    4   26   30
 /  \      /  \      /  \      /
20   25   25   21   25   4    2


List from binary tree : [13, 2, 2, 2, 13, 14, 1, 1, 1, 1, 19, 13, 4, 26, 30, 20, 25, 25, 21, 25, 4, 2]